OrdererOrgs:
  - Name: Orderer
    Domain: acornpub.com
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2

Orderer: &OrdererDefaults
  OrdererType: kafka
  Addresses:
    - orderer.acornpub.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Kafka:
    Brokers:
      - kafka1.acornpub.com:9092
      - kafka2.acornpub.com:9092
      - kafka3.acornpub.com:9092
      - kafka4.acornpub.com:9092
  Organizations:
  

PeerOrgs:
  - Name: Sales1
    Domain: sales1.acornpub.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Sales2
    Domain: sales2.acornpub.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Customer
    Domain: customer.acornpub.com
    Template:
      Count: 2
    Users:
      Count: 1
